#ifndef CONSTS_H
#define CONSTS_H

const int TILE_WIDTH = 8;
const int TILE_HEIGHT = 8;
const int GAME_WIDTH = 320;
const int GAME_HEIGHT = 200;
const int MAP_WIDTH = GAME_WIDTH/TILE_WIDTH;
const int MAP_HEIGHT = GAME_HEIGHT/TILE_HEIGHT - 1;
const int PLAYER_WIDTH[5] = {10, 0, 0, 0, 0};
const int PLAYER_HEIGHT[5] = {12, 0, 0, 0, 0};
const int EDITOR_SPACING_X = MAP_WIDTH * TILE_WIDTH / 2;
const int EDITOR_SPACING_Y = MAP_HEIGHT * TILE_HEIGHT / 2;
const int EDITOR_WIDTH = MAP_WIDTH * TILE_WIDTH + EDITOR_SPACING_X * 2;
const int EDITOR_HEIGHT = MAP_HEIGHT * TILE_HEIGHT + EDITOR_SPACING_Y * 2;

#endif
